/** ALL VALUES ARE IN MILLISECONDS */

/** The length of time before the access token expires. Should be the same as the actual value as the 
 *  'expiresIn' value of the token generated by the server
 */
const ACCESS_TOKEN_LIFETIME = 30 * 60 * 1000;

/** How long the user should remain authenticated if they have selected remember me.
 *  This value is overriden if the user is still active.
 */
export const PERSISTENCE_WINDOW =  8 * 60 * 60 * 1000;

/** How much time should elapse before a new access token is retrieved */
export const ACCESS_TOKEN_REFRESH_INTERVAL = 0.80 * ACCESS_TOKEN_LIFETIME;

/** The maximum time that a user is allowed to be inactive before the warning appears that 
 *  their authentication is about to expire.
 */
export const MAX_USER_INACTIVITY =  5 * 60 * 1000;

/** This is how it will take for the auth to expire after the user has received the warning
 *  for being inacitve.
 */
export const AUTH_WILL_EXPIRE_IN = 15 * 1000;
